# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15050db1b571c50844f36fcfea3d055f7768e9ee8b1355df1ec3552efdd05ed1f56e3e121594ed8876291405033c8285bc22b7a1c403a5293bf20c2d25d9480a

test:
  secret_key_base: 7bce41e3b8c3aebecbf17625a0c82305e90ee904ee84fb7aef751b25ff196a14e79b3bac45ad6c6d0f9628547a231603bd28aa498c9810f426e36207582c74d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
